data<-read.csv2("household_power_consumption.txt")
data
hpc<-subset(data, Date=="1/2/2007" |Date=="2/2/2007")
str(hpc)
sub1<-as.numeric(hpc$Sub_metering_1)
sub2<-as.numeric(hpc$Sub_metering_2)
sub3<-as.numeric(hpc$Sub_metering_3)
plot.ts(sub1,xlab=" ",ylab="Energy Sub Metering", xaxt ="n")
axis(1, at= c(0,1440,2880) ,lab=c("Thu","Fri","Sat"))
lines(sub2,col="red")
lines(sub3,col="blue")
legend("topright",pch="-",col= c("black","red","blue"),legend = c("Sub_metering_1","Sub_metering_2","Sub_metering_3"))
dev.copy(png,file="plot3.png")
dev.off()
